plugins {
    id 'java'
}

group 'org.example'
version '1.0.0'

repositories {
    mavenCentral()
    maven {
        url = "https://maven.pkg.github.com/eybv/jhttp-poc"
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_USER")
            password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

dependencies {
    implementation 'com.github.eybv:jhttp:1.0.3'
}
